version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: movie-service-db
    environment:
      POSTGRES_DB: movie_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
